In [16]:
#Scipy subpackage Integration *General Integration*
from scipy.integrate import quad

In [2]:
def integratefun(x):
    return x

In [11]:
#perform quad integration for function x for limits 0 and 1
quad(integratefun,0,1)

(0.5, 5.551115123125783e-15)

In [15]:
# define function for ax+b
def integratefunction(a,b,x):
    return x*a+b
    

In [13]:
a=3
b=2

In [14]:
quad(integratefunction,0,1,args=(a,b))

(4.0, 4.440892098500626e-14)

In [20]:
#Scipy subpackage Integration *Multiple Integration*
import scipy.integrate  as integrate

In [21]:
def f(x,y):
    return x+y
integrate.dblquad(f,0,1,lambda x: 0,lambda x: 2)

(7.105427357601005e-15, 5.0945755674135735e-14)

In [22]:
#Scipy subpackage Optimization
import numpy as np
from scipy import optimize

In [23]:
def f(x):
    return x**2 + 5*np.sin(x)

In [24]:
minval=optimize.minimize(f,x0=2,method='bfgs',options={'disp':True})

Optimization terminated successfully.
         Current function value: -3.246394
         Iterations: 5
         Function evaluations: 18
         Gradient evaluations: 9


In [25]:
minvalwithoutopt=optimize.minimize(f,x0=2,method='bfgs')

In [26]:
minvalwithoutopt

      fun: -3.2463942726915196
 hess_inv: array([[0.15445831]])
      jac: array([-4.47034836e-07])
  message: 'Optimization terminated successfully.'
     nfev: 18
      nit: 5
     njev: 9
   status: 0
  success: True
        x: array([-1.11051058])

In [28]:
#Optimize root of vector function
import numpy as np
from scipy.optimize import root
def rootfunc(x):
    return x + 3.5 * np.cos(x)

In [29]:
rootval=root(rootfunc,0.3)

In [30]:
rootval

    fjac: array([[-1.]])
     fun: array([0.])
 message: 'The solution converged.'
    nfev: 14
     qtf: array([-8.32889313e-13])
       r: array([-4.28198145])
  status: 1
 success: True
       x: array([-1.21597614])

In [31]:
#Scipy subpackage Linear Algebra
# 1 Inverse of matrix
import numpy as np
from scipy import linalg
matrix=np.array([[10,6],[2,7]])
matrix

array([[10,  6],
       [ 2,  7]])

In [32]:
type(matrix)

numpy.ndarray

In [33]:
linalg.inv(matrix)

array([[ 0.12068966, -0.10344828],
       [-0.03448276,  0.17241379]])

In [34]:
# Finding determinant of matrix
import numpy as np
from scipy import linalg
matrix=np.array([[4,9],[3,5]])
matrix

array([[4, 9],
       [3, 5]])

In [35]:
linalg.det(matrix)

-6.999999999999999

In [36]:
# Solve Linear Systems
import numpy as np
from scipy import linalg


In [37]:
numarr=np.array([[2,3,1],[-1,5,4],[3,2,9]])

In [38]:
numarrval=np.array([21,9,6])

In [39]:
linalg.solve(numarr,numarrval)

array([ 4.95,  4.35, -1.95])

In [40]:
# Single value decomposition
import numpy as np
from scipy import linalg

In [41]:
numSVDarr=np.array([[3,5,1],[9,5,7]])

In [43]:
linalg.svd(numSVDarr)

(array([[-0.37879831, -0.92547925],
        [-0.92547925,  0.37879831]]),
 array([13.38464336,  3.29413449]),
 array([[-0.7072066 , -0.4872291 , -0.51231496],
        [ 0.19208294, -0.82977932,  0.52399467],
        [-0.68041382,  0.27216553,  0.68041382]]))

In [44]:
#Scipy subpackage Statistics
from scipy.stats import norm


In [50]:
#rvs for random variables
norm.rvs(loc=0,scale=1,size=10)

array([-0.40930284, -0.1119171 , -1.20503588,  0.0733258 ,  0.58393779,
       -0.74136596,  0.40505354,  0.18175886,  0.19230511, -1.94549305])

In [52]:
#standard local districution is the mean and scale is the standard devation
norm.cdf(5,loc=1,scale=2)

0.9772498680518208

In [53]:
norm.pdf(9,loc=0,scale=1)

1.0279773571668917e-18